creation_rules:
  - path_regex: nomad/config/democratic-csi-iscsi-controller.yml
    encrypted_suffix: Key
    key_groups:
      - age:
        - age1cn8jcfpmkyr2f6q3xxe5k8uwvk0apk0ma9psv3kxdvr8fuh45e6smry3ks
stores:
  yaml:
    indent: 2
