access_key_id: ENC[AES256_GCM,data:BxgVjsOxcDDchBjR9+kR0U1Uixk=,iv:qhN28KIi7pGdvcziEe8z2ZlHDHRw3OBH/ASjpfjQFnc=,tag:cCFU1cQRKnxjunmYXPUoRA==,type:str]
secret_access_key: ENC[AES256_GCM,data:1ZCpy3K50dObwHCO2pEyn0nT7KyMpKrYeJTJVoRYqHoymtYlfSsa5A==,iv:r/GvzSzMoHCzlkxOmS3CepfjQpuCBCoG1CX27QKYd6I=,tag:ic9rR+yab7LnI9/8UnQ7EQ==,type:str]
sops:
  age:
    - recipient: age1cn8jcfpmkyr2f6q3xxe5k8uwvk0apk0ma9psv3kxdvr8fuh45e6smry3ks
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlcFk3TXNXLzk3UWczMnpx
        c0VRZm40NXg1Ukp0anlITUt2by9vQmhhTVZvCkJNcWd2S1Y3T3kwMHpBZ0swRDFu
        dldyUnFUVy9BT0tLSUJDMmE5VmtkRkUKLS0tIHd0UmwzMktXVThQVmV0WlI2bENy
        K0xEeS9rRWJFbUFrMW13am9DcHRtMHcKWu5NStqm43R+FYRYervPGXmo7CaHtUpP
        TXQRaO7Rhi2nMIOwHgJ5WQNfZA7JKj4ml4sRajUks4YfK19rN9hhWA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-11T17:06:35Z"
  mac: ENC[AES256_GCM,data:YGEdGEc+ftZSZtfKNSauamemTfFbZLm41vy2bOFOoEZLj8T914dulMqlayrIhW4LdnF7lwKzvhDZOtsMiWbMu1+y0m8wOpjA4p/5z+HHrcBVhcYuxrvuZegtWjvsstzhKqyzh7SBdM3IVIoDwJvQeTY/Kf0wvczKI2IyuX4U1Eo=,iv:dnZfj8gY+GE2w/3/Cxv3bEJI/3q8PgMMeCMQbS0oESg=,tag:aVUlC3o62+xRxXq4FXZQlg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.10.2
